export { default as HomeLayout } from "./homeLayout"
export { default as GroupChatLayout } from "./groupChatLayout"
export { default as GroupLayout } from "./groupLayout"
export { default as TimeTableLayout } from "./timeTableLayout"
export { default as LandingPageLayout } from "./landingPageLayout"
export { default as SignLayout } from "./signLayout"
export { default as TeamWorkLayout } from "./teamWorkLayout"
export { default as DevelopLayout } from "./developLayout"