export { default as AddLectures } from "./develop/addLectures"
export { default as GenTeacherSign } from "./develop/genTeacherSign"
export { default as GenCompanySign } from "./develop/genCompanySign"
export { default as DevelopHome } from "./develop/developHome"
export { default as TeacherSignup } from "./teacherSignup"
export { default as TeacehrHome } from "./teacherHome"
