const account = require("./api/account")
const group = require("./api/group")
const course = require("./api/course")
const teamWork = require("./api/teamWork")
const timeTable = require("./api/timeTable")
const generateLink = require("./api/generateLink")
const post = require("./api/post")
const check = require("./api/check")
const company = require("./api/company")
const teacher = require("./api/teacher")

const express = require("express")

const app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.listen(4000, () => console.log("open port 4000"))

app.use("/account", account)
app.use("/group", group)
app.use("/course", course)
app.use("/teamWork", teamWork)
app.use("/timeTable", timeTable)
app.use("/generateLink", generateLink)
app.use("/post", post)
app.use("/check", check)
app.use("/company", company)
app.use("/teacher", teacher)