export { default as CompanySignup } from "./companySignup"
export { default as CompanyHome } from "./companyHome"
export { default as CompanyProfileEdit } from "./companyProfileEdit"
export { default as StudentProfileView } from "./studentProfileView"
export { default as CompanyNews } from "./companyNews"